### ISSUE TITLE
Example of plugin which interacts with DB

### ISSUE THREAD

**Issue by Grazouillis** [bludit/examples#1]
Hello,

I read this [doc to make a simple plugin](https://docs.bludit.com/en/plugins/plugin-basics).

Is it possible to make a tutorial which learns how to make a plugin that interacts with the database please? :)

Thanks a lot !

**Comment by clickwork-git** [comment]
What do you mean with "interacts with the database"? Which database? The database file? And what do you mean with interaction?

Can you please give an example.

**Comment by Grazouillis** [comment]
I would like to create 2 plugins :
- comments on posts without account (as Nibbleblog has -- not disqus, because I would like that members be able to comment without any account)
- like on posts without account too (basic, from encrypted ip address)

I confess that I don't understand how a flat database works as uses bludit (so far, I've always used mysql, mariaDB, so I'm lost here because I don't know what is the structure), I don't know what schema exists, how to use pre-existing post keys and so on... 

With nibbleblog, Diego created [this](http://docs.nibbleblog.com/index.php?controller=post&action=view&id_post=16) . It would be nice if we could have the same for Bludit... A guideline to go further than a message in the sidebar... :)

**Comment by clickwork-git** [comment]
There is no sense to allow comments without registration and administration except you would like to be overflowed by spam... On the other hand the administration of comments has become much more complicated by the GDPR.

Perhaps there will be an own commenting system in the future, but it has no priority.

At the moment there are several possibilities to add comments:

https://forum.bludit.org/viewtopic.php?f=6&t=1147&p=5102

The easiest way to learn how to code a plugin is to have a look at the existing plugins. They are good examples what can be done.
